apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iaf-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iaf-controller-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: iaf-system
